version: '3.7'
services:
    app:
        container_name: vuttr-cliente
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3001:3001'
        environment:
            - NODE_ENV=development